apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: 060704331174.dkr.ecr.ap-south-1.amazonaws.com/rest-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
