apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: YOUR_DOCKERHUB_USERNAME/rest-api-with-docker:1.0
          ports:
            - containerPort: 8080