apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rest-api-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
        - name: rest-api
          image: tapanaws155/rest-api-with-docker:1.0
          ports:
            - containerPort: 8080